
POST http://localhost:3000/users/login
content-type: application/json

{
    "username": "sample",
    "password": "sampling"
}

###

DELETE http://localhost:3000/users/662feb441f4d170f050ce528

###

GET http://localhost:3000/users

###

GET http://localhost:3000/users/6633292202547ea078c61684

###

GET http://localhost:3000/users/6633292202547ea078c61684/algomas

###

POST http://localhost:3000/users
content-type: application/json

{
    "email": "sample10@hotmail.com",
    "name": "sample10",
    "password": "password10",
    "profileImage": "",
    "userName": "sampling10"
}

###

PUT http://localhost:3000/users/6633292202547ea078c61684
content-type: application/json

{
    "name": "sample8-2",
    "email": "sample8-2@hotmail.com",
    "userName": "sampling8-2",
    "password": "P4$$w0rd8-2",
    "profileImage": "image8-2"
}
